train_dataloader:
  type: DataLoader
  dataset:
    type: MPEblinkV2Dataset
    ann_file: /data/data4/zengwenzheng/data/dataset_building/mpeblink_cvpr2023/annotations/train.json
    img_fold: /data/data4/zengwenzheng/data/dataset_building/mpeblink_cvpr2023/train_rawframes/
    stride: 12
    infer_length: 24
    clip_length: 24
    frame_interval: 2
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion
    
  total_batch_size: 2 # 4 * 4
  num_workers: 1


val_dataloader:
  type: DataLoader
  dataset:
    type: MPEblinkV2Dataset
    ann_file: /data/data4/zengwenzheng/data/dataset_building/mpeblink_cvpr2023/annotations/val.json
    img_fold: /data/data4/zengwenzheng/data/dataset_building/mpeblink_cvpr2023/val_rawframes/
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion