__include__: [
  '../dataset/mpeblink_len=10_abla_v2.yml',
  '../runtime.yml',
  './include/dataloader_len=10.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd_abla.yml',
]

output_dir: ./output/rtdetrv2_r50vd_6x_coco_len=10_mpeblinkv2_abla

last_epoch: 0

epoches: 1
